---

- name: include os specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family }}.yml'
  tags:
    - 'role::sesam_server'
    - 'role::sesam_server:install'
    - 'role::sesam_server:config'
    - 'role::sesam_server:ssl'

- import_tasks: installation.yml
  tags:
    - 'role::sesam_server'
    - 'role::sesam_server:install'

- import_tasks: configuration.yml
  tags:
    - 'role::sesam_server'
    - 'role::sesam_server:config'

      #- import_tasks: ssl.yml
      #tags:
      #- 'role::mariadb'
      #- 'role::mariadb:ssl'
      #when: mariadb_ssl
